apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions
spec:
  selector:
    matchLabels:
      app: actions
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: actions
        role: actions
    spec:
      containers:
        - name: actions
          image: itzelmunguia/demo-actions:latest
          ports:
            - containerPort: 80
              name: actions

---
apiVersion: v1
kind: Service
metadata:
  name: actions
  labels:
    app: actions
spec:
  selector:
   app: actions
  type: LoadBalancer
 # loadBalancerIP: 148.213.1.154
  ports:
   - name: http
     port: 80
     protocol: TCP
     targetPort: 80
  selector:
    role: actions
